module.exports = {
  intent: 'ket_qua_hoc_tap',
  patterns: [
    'Điểm trung bình hệ 4 kỳ này là bao nhiều?',
    'Điểm trung bình hệ số 10 kỳ này là bao nhiều?',
    'Điểm trung bình kỳ này là bao nhiều?',
    'Bao nhiêu điểm là đủ ra trường?',
    'Bao nhiêu điểm là được bằng khá?',
    'Bao nhiêu điểm là được bằng giỏi?',
    'Bao nhiêu điểm là có học bổng?',
    'Bao nhiêu điểm là đủ ra trường?',
    'Mấy điểm là được bằng khá?',
    'Mấy điểm là được bằng giỏi?',
    'Mấy điểm là có học bổng?',
    'Mấy điểm có thể làm khóa luận tốt nghiệp?',
    'Kết quả học tập hệ sô 4 kỳ này là bao nhiều?',
    'Kết quả học tập hệ số 10 kỳ này là bao nhiều?',
    'Kết quả học tập kỳ này là bao nhiều?',
    'Kết quả học tập bao nhiêu là được bằng khá?',
    'Kết quả học tập bao nhiêu là được bằng giỏi?',
    'Kết quả học tập bao nhiêu là có học bổng?',
    'Kết quả học tập bao nhiêu có thể làm khóa luận tốt nghiệp?',
  ],
  responses: [],
}